pygments : true
#Reset when committing!
usegoogleanalytics : true
#Reset when committing!
localmode : false
plugins: 
  - name : 'jQuery.GitHubBadge'
    link : '/jQuery.GitHubBadge'
    description : 'Adds a badge listing your GitHub account public repositories'
    language : 'Javascript'
    platform : 'Web'
    modified : 03-05-2009
    created : 03-05-2009
  - name : 'jQuery.printElement'
    link : '/jQuery.printElement'
    description : 'Sends an element to print, either in a popup or a hidden iframe'
    language : 'Javascript'
    platform : 'Web'
    modified : 09-10-2009
  - name : 'jQuery.LateLoader'
    link : '/jQuery.LateLoader'
    description : 'Late loading of scripts and CSS files'
    language : 'Javascript'
    platform : 'Web'
    modified : 16-07-2009
    created : 16-07-2009
#placeholder
templateforprojects:
  - name : 'jQuery Plugins1'
    link : '/jQueryPlugins1'
    description : 'Collecti1on of jQuery plugins'
    language : 'Javascript1'
    platform : 'Web1'
    modified : 03-08-1999
    created : 03-05-2009
  - name : 'jQuery Plugins2'
    link : '/jQueryPlugins2'
    description : 'Collecti21on of jQuery plugins'
    language : 'Javascript12'
    platform : 'Web12'
    modified : 03-08-1999
    created : 03-05-2009
